"""
CanAdapterSource: taps the physical CAN bus directly, bypassing the Nucleo hub.

Every other live source (SerialSource in sources.py) reads the ALREADY
REASSEMBLED radio/USB frame the hub built from CAN traffic. This source skips
the hub entirely and does the hub's own job in Python: it opens a USB-CAN
adapter (CANable/slcan, PCAN, Kvaser, socketcan on Linux, ...) via the
python-can library, watches raw CAN traffic for this project's node IDs, and
reassembles the paged per-node messages back into the same proto_v2.Frame
object SerialSource yields. Point of this: bench-testing nodes with no hub
present, or debugging the hub's own reassembly by running an independent
decode of the same bus traffic side by side with it.

--------------------------------------------------------------------------
python-can is OPTIONAL
--------------------------------------------------------------------------
Nobody without a USB-CAN adapter should pay for this feature. In particular
the frozen Telemetry.exe (see build.bat) ships to people with a serial dongle
and nothing else, and `import telemetry.can_adapter` happens unconditionally
wherever run.py wires up --source choices - so this module must import
cleanly with python-can absent from the environment. The only import of
`can` lives inside CanAdapterSource.__init__, exactly like SerialSource does
for pyserial at module scope, except pushed one level deeper: pyserial is a
required dependency of this app (aiohttp/pyserial are "the whole runtime"
per requirements.txt) so sources.py can import it at module scope and just
check `serial is None` at use time. python-can has no such free pass, so the
import itself is deferred to first use rather than attempted-and-nulled at
import time - either approach keeps a missing library from being fatal at
startup, but deferring to __init__ also means the ImportError's message (the
`raise ... from exc` below) gets seen exactly once, when someone actually
asks for --source can, instead of being swallowed silently at import time
the way `can = None` would be.

--------------------------------------------------------------------------
Decode choice: proto_v2's own pack/reassembly helpers, not cantools + the DBC
--------------------------------------------------------------------------
protocol/telemetry_v2.dbc exists (generated by tools/gen_dbc_v2.py) and
cantools could decode every page's signals from it. Rejected that in favor of
reusing proto_v2.NodeReassembler / proto_v2.can_id_for / _from_id /
_LAYOUTS-backed pack_pages directly, for one reason: tools/test_dbc_v2.py's
whole job is proving the DBC and the firmware's C packing AGREE - it does not
make the DBC an independent source of truth, it makes it a mirror of
proto_v2.py, which is itself already the byte-for-byte-tested mirror of the
C source (see proto_v2.py's own module docstring, and
tools/test_roundtrip_v2.py). Decoding through cantools here would be a THIRD
copy of the same channel table, with its own way to quietly drift the moment
someone adds a channel and regenerates the DBC without regenerating whatever
static copy this file would otherwise keep. Going through proto_v2 directly
means this file has zero channel-table knowledge of its own: NODE_COUNT,
CHANNELS, CAN_DATA_BASE_ID, page layout, all come from the one already-tested
module, and a channel-table change here requires touching nothing in this
file at all.

--------------------------------------------------------------------------
Reassembly
--------------------------------------------------------------------------
proto_v2.NodeReassembler already implements everything the CAN layer needs to
get from raw pages to a NodeRecord.online/.stale flags, fresh-epoch detection
that discards a torn burst, and epoch-gap loss accounting - because it is the
exact same class the hub firmware's Python mirror uses to model
tlm2_reasm_apply_page/tlm2_reasm_snapshot. This module's only job is to (a)
route each incoming can.Message to the right NodeReassembler by CAN ID, and
(b) call .snapshot() on all NODE_COUNT of them once every FRAME_PERIOD_MS to
produce a Frame, the same cadence the hub's s_next_frame_ms tick uses in
telemetry_hub_v2.c. A node that goes silent is not a hang: NODE_TIMEOUT_MS
inside snapshot() marks it NF_STALE automatically, same as it would for the
real hub losing contact with a node.

--------------------------------------------------------------------------
Bitrate
--------------------------------------------------------------------------
proto_v2.CAN_BITRATE = 500_000 (proto_v2.py line 57). Cross-checked against
the firmware: firmware/projects/1st Bluepill/Core/Inc/telemetry_proto_v2.h
defines TLM2_CAN_BITRATE as 500000u with the comment "same physical bus as
v1", and firmware/CUBEMX_SETUP.md's CubeMX walkthrough lists "Baud Rate:
500000" for the bxCAN peripheral setup. All three agree, so the default here
is proto_v2.CAN_BITRATE rather than a literal, so a future bus-speed change
only has to happen in one place.
"""

from __future__ import annotations

import asyncio
import logging
import time
from typing import AsyncIterator

from .protocols import active
from .proto import Frame  # noqa: F401 - type annotations only; runtime
                          # construction goes through active() below, same
                          # convention sources.py uses.
from .sources import FrameSource, LINK_ERROR, LINK_LIVE, LINK_WAITING

log = logging.getLogger("telemetry")


class CanAdapterSource(FrameSource):
    """
    Live CAN bus source via python-can (CANable/slcan, PCAN, Kvaser,
    socketcan, ...). Matches FrameSource's contract exactly: .name,
    .link_state, .detail are kept current, frames() never raises for a
    recoverable condition (adapter unplugged, node gone quiet, foreign
    traffic on the bus), and close()/stats() are implemented the same shape
    as SerialSource's.

    Requires the ACTIVE protocol (see protocols.py) to be v2. v1 packs a
    fixed 3xint16 record into one CAN frame per node with no paging at all,
    so there is no NodeReassembler for it to reuse; rather than half-support
    that with separate code paths, this source simply refuses to construct
    under v1 and says so, the same way SimulatorSource already refuses to
    build v1-shaped frames when asked for something it cannot produce.
    """

    RETRY_DELAY = 2.0

    def __init__(
        self,
        channel: str,
        interface: str = "slcan",
        bitrate: int | None = None,
        reconnect: bool = True,
    ) -> None:
        # Deferred import - see module docstring. Only reached when someone
        # actually constructs this source, i.e. asked for --source can.
        try:
            import can  # type: ignore[import-untyped]
        except ImportError as exc:
            raise RuntimeError(
                "python-can is not installed - run: pip install python-can\n"
                "Then construct CanAdapterSource with the channel/interface "
                "for your adapter, e.g.:\n"
                '  CanAdapterSource(channel="COM7", interface="slcan")        '
                "# CANable running slcan firmware on Windows\n"
                '  CanAdapterSource(channel="can0", interface="socketcan")    '
                "# Linux SocketCAN\n"
                '  CanAdapterSource(channel="PCAN_USBBUS1", interface="pcan") '
                "# PEAK PCAN-USB"
            ) from exc

        self._can = can

        proto = active()
        if not hasattr(proto, "NodeReassembler"):
            # v1 selected. See class docstring - there is nothing correct to
            # reassemble here, so fail loudly and immediately rather than
            # producing an always-empty or subtly-wrong Frame stream.
            raise RuntimeError(
                "CanAdapterSource requires the v2 protocol (its paged CAN "
                "layout and NodeReassembler); the active protocol is "
                f"{proto.PROTO_VERSION:#x}. Select v2 first (protocols.use('v2') "
                "/ --proto v2 in run.py) before building this source."
            )
        self._proto = proto

        self.channel = channel
        self.interface = interface
        self.bitrate = bitrate if bitrate is not None else proto.CAN_BITRATE
        self.reconnect = reconnect

        self.name = f"can {interface}:{channel} @ {self.bitrate}"
        self.link_state = LINK_WAITING
        self.detail = "not connected yet"

        self.connects = 0
        self.disconnects = 0
        self.can_rx = 0        # frames matched to a project node/page
        self.can_foreign = 0   # everything else on the bus - mirrors
                                # hub2_stats_t.can_foreign in telemetry_hub_v2.c
        self.frames_built = 0
        self.last_rx_at: float | None = None

        self._bus = None
        self._t0 = time.monotonic()
        self._seq = 0
        self._reasm = [proto.NodeReassembler(n) for n in range(proto.NODE_COUNT)]

    # ---------------- connection management ----------------

    def _open(self) -> bool:
        try:
            # can.Bus (not the older can.interface.Bus alias) is python-can's
            # documented modern entry point; it dispatches to the right
            # backend class from the interface= string.
            self._bus = self._can.Bus(
                channel=self.channel, interface=self.interface, bitrate=self.bitrate
            )
        except Exception as exc:  # noqa: BLE001 - python-can raises a different
                                   # exception type per backend (CanInitializationError,
                                   # OSError from pyserial under slcan, etc.); the
                                   # thing that matters here is "could not open",
                                   # not which backend-specific class it was.
            self.link_state = LINK_ERROR
            self.detail = f"{self.interface}:{self.channel}: {exc}"
            self._bus = None
            return False

        self.link_state = LINK_LIVE
        self.detail = "connected"
        self.connects += 1
        log.info(
            "CAN adapter connected: %s:%s @ %d", self.interface, self.channel, self.bitrate
        )
        return True

    def _drop(self, why: str) -> None:
        if self._bus is not None:
            try:
                self._bus.shutdown()
            except Exception:  # noqa: BLE001
                pass
            self._bus = None
            self.disconnects += 1
            log.warning("CAN adapter disconnected: %s", why)

        self.link_state = LINK_WAITING if self.reconnect else LINK_ERROR
        self.detail = why

    def _recv(self, timeout: float):
        """Blocking receive of one message, run in the executor thread - same
        reasoning as SerialSource._read(): python-can backends block on I/O,
        so this must not run on the event loop thread."""
        bus = self._bus
        if bus is None:
            return None
        return bus.recv(timeout=timeout)

    def _now_ms(self) -> int:
        return int((time.monotonic() - self._t0) * 1000.0) & 0xFFFFFFFF

    # ---------------- message routing ----------------

    def _handle_message(self, msg) -> None:
        # Error frames and remote-transmission-request frames carry no node
        # data and are not "foreign" traffic in the can_foreign sense (that
        # counter mirrors the hub's count of real, addressed frames that
        # just are not ours) - they are bus-level noise, so they are dropped
        # here without touching any counter.
        if getattr(msg, "is_error_frame", False) or getattr(msg, "is_remote_frame", False):
            return

        self.last_rx_at = time.time()

        # Extended (29-bit) IDs are never used by this project (CAN_DATA_BASE_ID
        # and friends are all well inside the 11-bit standard ID space) - the
        # hub firmware's own ISR treats a non-standard-ID frame as foreign
        # (see HAL_CAN_RxFifo0MsgPendingCallback: `header.IDE != CAN_ID_STD`
        # goes straight to can_foreign++), so this mirrors that.
        if getattr(msg, "is_extended_id", False):
            self.can_foreign += 1
            return

        can_id = msg.arbitration_id

        # Deliberately NOT using can.Bus(can_filters=...) to have the driver
        # do this filtering in hardware. That would be cheaper on a busy bus,
        # but it would also mean can_foreign never sees the traffic it is
        # supposed to be counting - the whole point of that counter (and the
        # firmware's identical one) is visibility into how much of the bus is
        # NOT this project's telemetry, e.g. another team's ECU sharing the
        # same physical bus. Software filtering here keeps that visibility.
        if not self._proto.can_id_is_node(can_id):
            self.can_foreign += 1
            return

        node = self._proto.can_node_from_id(can_id)
        page = self._proto.can_page_from_id(can_id)

        # Defensive pad/truncate to CAN_DLC bytes. A well-behaved adapter
        # always hands back exactly msg.dlc bytes of data and this project
        # always sends DLC 8, but NodeReassembler.apply_page indexes d8[0],
        # d8[1] and offsets up to 2+PAGE_PAYLOAD_SIZE unconditionally; a
        # short/malformed frame from a flaky adapter should be dropped as
        # noise, not raise out of frames() and take the whole source down.
        data = bytes(msg.data)
        if len(data) < self._proto.CAN_DLC:
            self.can_foreign += 1
            return
        data = data[: self._proto.CAN_DLC]

        # apply_page() itself is the authority on whether (node, page) is
        # sane - see its own "bogus node/page" comment in proto_v2.py. It
        # returns False (nothing published) rather than raising, both for a
        # bad page index and for a page that only completes part of a
        # snapshot, so nothing further is needed here to handle either.
        self._reasm[node].apply_page(page, data, self._now_ms())
        self.can_rx += 1

    def _build_frame(self) -> Frame:
        now_ms = self._now_ms()
        records = [self._reasm[n].snapshot(now_ms) for n in range(self._proto.NODE_COUNT)]
        frame = self._proto.Frame(seq=self._seq & 0xFFFF, t_ms=now_ms, nodes=records)
        self._seq += 1
        self.frames_built += 1
        return frame

    # ---------------- iteration ----------------

    async def frames(self) -> AsyncIterator[Frame]:
        loop = asyncio.get_running_loop()
        period = self._proto.FRAME_PERIOD_MS / 1000.0
        next_at = time.monotonic() + period

        while True:
            if self._bus is None:
                if not self._open():
                    if not self.reconnect:
                        return
                    await asyncio.sleep(self.RETRY_DELAY)
                    next_at = time.monotonic() + period
                    continue

            # Block for messages only up until the next snapshot is due, so a
            # quiet bus still produces on-time (all-stale) Frames instead of
            # frames() stalling forever waiting on recv(). Mirrors the hub's
            # own split between an interrupt-driven RX path and an
            # independent periodic snapshot tick (s_next_frame_ms).
            timeout = max(0.0, next_at - time.monotonic())
            try:
                msg = await loop.run_in_executor(None, self._recv, timeout)
            except asyncio.CancelledError:
                raise
            except Exception as exc:  # noqa: BLE001 - backend-specific I/O errors
                self._drop(str(exc))
                if not self.reconnect:
                    return
                await asyncio.sleep(self.RETRY_DELAY)
                next_at = time.monotonic() + period
                continue

            if msg is not None:
                self._handle_message(msg)

            if time.monotonic() >= next_at:
                next_at += period
                yield self._build_frame()

    async def close(self) -> None:
        if self._bus is not None:
            try:
                self._bus.shutdown()
            except Exception:  # noqa: BLE001
                pass
            self._bus = None

    def stats(self) -> dict:
        return {
            "channel": self.channel,
            "interface": self.interface,
            "bitrate": self.bitrate,
            "connects": self.connects,
            "disconnects": self.disconnects,
            "can_rx": self.can_rx,
            "can_foreign": self.can_foreign,
            "frames_built": self.frames_built,
        }
