#!/usr/bin/env python3
"""
Generate protocol/telemetry.dbc from the channel table.

    python tools/gen_dbc.py

A DBC describes a whole CAN *network*, not a single ECU: it lists the nodes
(BU_) and every message on the bus (BO_), each tagged with which node sends it.
So three nodes means one file with three messages, not three files. That is what
SavvyCAN, BusMaster, Vector CANalyzer, PCAN-Explorer and python-can/cantools
all expect, and it is why splitting per node would actually make the file
harder to use - each fragment would describe a bus with one participant.

The file is generated rather than hand-written so it cannot drift from
TLM_CHANNELS in telemetry_proto.c. tools/test_dbc.py decodes real frames
through both the DBC and proto.py and compares, which is what makes that
guarantee mean something.
"""

from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "pc_app"))

from telemetry import proto  # noqa: E402

OUT = ROOT / "protocol" / "telemetry.dbc"

# Short node names. DBC identifiers allow letters, digits and underscore only,
# and many tools truncate or choke on anything longer than about 32 chars.
NODE_NAMES = ["NODE0_ENV", "NODE1_PWR", "NODE2_MOT"]
RECEIVER = "HUB"

# Status bits, from TLM_ST_* in telemetry_proto.h. Broken out as named 1-bit
# signals rather than one opaque byte: a dashboard showing "SENSOR_FAULT = 1"
# is useful, "status = 5" is a puzzle.
STATUS_BITS = [
    (0, "sensor_fault", "Node could not read a sensor"),
    (1, "startup", "Within the first two seconds after reset"),
    (2, "can_error", "Node saw bus errors or recovered from bus-off"),
]


def signal_line(name: str, start: int, length: int, signed: bool,
                scale: float, offset: float, unit: str) -> str:
    """
    One SG_ entry.

    Byte order is @1 (Intel / little-endian), matching the memcpy-based packing
    in tlm_can_pack(). Getting this backwards is the classic DBC mistake: the
    values still decode, they are just wrong in a way that looks like noise.
    """
    span = (1 << length)
    if signed:
        lo = (-(span // 2)) * scale + offset
        hi = (span // 2 - 1) * scale + offset
    else:
        lo = offset
        hi = (span - 1) * scale + offset

    sign = "-" if signed else "+"

    def num(v: float) -> str:
        # DBC readers are happier with plain decimals than exponent notation.
        s = f"{v:.6f}".rstrip("0").rstrip(".")
        return s if s else "0"

    return (f' SG_ {name} : {start}|{length}@1{sign} '
            f'({num(scale)},{num(offset)}) [{num(lo)}|{num(hi)}] "{unit}" {RECEIVER}')


def build() -> str:
    L: list[str] = []

    L.append('VERSION "CAN-LoRa telemetry, protocol version '
             f'{proto.PROTO_VERSION}"')
    L.append("")
    L.append("")

    # The NS_ block is boilerplate every DBC carries. Tools that write DBCs
    # emit the full list; tools that read them expect the section to exist.
    L.append("NS_ :")
    for tag in ["NS_DESC_", "CM_", "BA_DEF_", "BA_", "VAL_", "CAT_DEF_", "CAT_",
                "FILTER", "BA_DEF_DEF_", "EV_DATA_", "ENVVAR_DATA_",
                "SGTYPE_", "SGTYPE_VAL_", "BA_DEF_SGTYPE_", "BA_SGTYPE_",
                "SIG_TYPE_REF_", "VAL_TABLE_", "SIG_GROUP_", "SIG_VALTYPE_",
                "SIGTYPE_VALTYPE_", "BO_TX_BU_", "BA_DEF_REL_", "BA_REL_",
                "BA_DEF_DEF_REL_", "BU_SG_REL_", "BU_EV_REL_", "BU_BO_REL_",
                "SG_MUL_VAL_"]:
        L.append(f"    {tag}")
    L.append("")
    L.append("BS_:")
    L.append("")

    L.append(f"BU_: {' '.join(NODE_NAMES)} {RECEIVER}")
    L.append("")

    # ---- messages ----
    for node in range(proto.NODE_COUNT):
        can_id = proto.CAN_DATA_BASE_ID + node
        msg = f"{NODE_NAMES[node]}_DATA"

        L.append(f"BO_ {can_id} {msg}: {proto.CAN_DLC} {NODE_NAMES[node]}")

        for i, ch in enumerate(proto.CHANNELS[node]):
            L.append(signal_line(ch.name, i * 16, 16, True,
                                 ch.scale, ch.offset, ch.unit))

        L.append(signal_line("seq", 48, 8, False, 1, 0, ""))

        for bit, name, _ in STATUS_BITS:
            L.append(signal_line(name, 56 + bit, 1, False, 1, 0, ""))

        L.append("")

    # ---- comments ----
    L.append(f'CM_ "Generated by tools/gen_dbc.py on '
             f'{datetime.now():%Y-%m-%d}. Do not edit by hand - '
             f'edit TLM_CHANNELS in protocol/telemetry_proto.c and regenerate.";')

    for node in range(proto.NODE_COUNT):
        can_id = proto.CAN_DATA_BASE_ID + node
        msg = f"{NODE_NAMES[node]}_DATA"
        L.append(f'CM_ BU_ {NODE_NAMES[node]} "STM32F103C8 Bluepill, '
                 f'{proto.NODE_LABELS[node].lower()} node";')
        L.append(f'CM_ BO_ {can_id} "{proto.NODE_LABELS[node]} readings, '
                 f'sent every {proto.NODE_TX_PERIOD_MS} ms";')
        L.append(f'CM_ SG_ {can_id} seq "Rolling counter, +1 per transmission. '
                 f'The hub uses gaps in this to measure frame loss.";')
        for bit, name, desc in STATUS_BITS:
            L.append(f'CM_ SG_ {can_id} {name} "{desc}";')

    L.append(f'CM_ BU_ {RECEIVER} "STM32L476RG, aggregates the bus and '
             f'uplinks snapshots over LoRa";')
    L.append("")

    # ---- attributes ----
    L.append('BA_DEF_ BO_  "GenMsgCycleTime" INT 0 65535;')
    L.append('BA_DEF_ "BusType" STRING ;')
    L.append('BA_DEF_DEF_  "GenMsgCycleTime" 0;')
    L.append('BA_DEF_DEF_  "BusType" "CAN";')
    L.append('BA_ "BusType" "CAN";')

    for node in range(proto.NODE_COUNT):
        can_id = proto.CAN_DATA_BASE_ID + node
        L.append(f'BA_ "GenMsgCycleTime" BO_ {can_id} {proto.NODE_TX_PERIOD_MS};')

    L.append("")

    # ---- value descriptions ----
    for node in range(proto.NODE_COUNT):
        can_id = proto.CAN_DATA_BASE_ID + node
        for _, name, _ in STATUS_BITS:
            L.append(f'VAL_ {can_id} {name} 1 "yes" 0 "no";')

    L.append("")
    return "\n".join(L)


def main() -> int:
    text = build()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")

    n_sig = proto.NODE_COUNT * (proto.CH_PER_NODE + 1 + len(STATUS_BITS))
    print(f"Wrote {OUT.relative_to(ROOT)}")
    print(f"  {proto.NODE_COUNT} nodes, {proto.NODE_COUNT} messages, {n_sig} signals")
    print(f"  IDs 0x{proto.CAN_DATA_BASE_ID:03X}"
          f"-0x{proto.CAN_DATA_BASE_ID + proto.NODE_COUNT - 1:03X}, "
          f"{proto.CAN_BITRATE // 1000} kbit/s")
    return 0


if __name__ == "__main__":
    sys.exit(main())
